name: Deploy ToDo+ App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Déploiement des fichiers sur le VPS via SCP
        run: |
          echo "Déploiement des dossiers frontend et backend..."
          scp -o StrictHostKeyChecking=no -r ./frontend ./backend ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}
        env:
          SSH_PASS: ${{ secrets.VPS_PASSWORD }}
